CREATE DATABASE OnlineStoreDatabase
USE OnlineStoreDatabase

CREATE TABLE Cities
(
	CityID INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
	CustomerID INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT FOREIGN KEY 
		REFERENCES Cities(CityID)
)

CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY,
	CustomerID INT FOREIGN KEY
		REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT PRIMARY KEY, 
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	ItemTypeID INT FOREIGN KEY 
		REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems
(
	OrderID INT NOT NULL FOREIGN KEY
		REFERENCES Orders(OrderID),
	ItemID INT NOT NULL FOREIGN KEY
		REFERENCES Items(ItemID)
    CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID, ItemID) 
)
